server:
  port: 8092
  context-path: /blog-search
mybatis:
  type-aliases-package: com.yy.domain
  config-location: classpath:sqlmap/sqlmap-config.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    #redis数据库索引(默认为0)
    database: 0
    #redis服务器地址
    host: 112.74.40.100
    #端口
#    port: 6379
    port: 8087
    #redis服务器连接密码(默认为空)
    password:
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5000
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 112.74.40.100:9092,112.74.40.100:8090
    consumer:
      bootstrap-servers: 112.74.40.100:9092,112.74.40.100:8090
      group-id: article-test
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    elasticsearch:
      cluster-name: elasticsearch
      #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      cluster-nodes: 112.74.40.100:8085
      properties:
        path:
          #elasticsearch日志存储目录
          logs: ./elasticsearch/log
          #elasticsearch数据存储目录
          data: ./elasticsearch/data
  dubbo:
    application:
      name: blog-search-provider
    registry:
      address: zookeeper://112.74.40.100:2181
    protocol:
      name: dubbo
      port: 20883
    scan: com.yy.service,com.yy.blog
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  trackerList: 45.77.113.201:22122
